// AUTO-GENERATED by obsidian-smart-env/build/build_env_config.js. DO NOT EDIT.






export const smart_env_config = {
  collections: {

  },
  item_types: {

  },
  items: {

  },
  modules: {

  },
  components: {

  },
  actions: {

  }
};
